### ISSUE TITLE
error:'_5_batch_join/fifo_queue' is closed and has insufficient elements (requested 256, current size 0)

### ISSUE THREAD

**Issue by molyswu** [Joker316701882/Additive-Margin-Softmax#17]
Hi,I compiled for python  train.py  with lfw datasets,as follow error:
OutOfRangeError (see above for traceback): FIFOQueue '_5_batch_join/fifo_queue' is closed and has insufficient elements (requested 256, current size 0)
	 [[Node: batch_join = QueueDequeueUpToV2[component_types=[DT_FLOAT, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_join/fifo_queue, _arg_batch_size_0_0)]]

Thanks for your help

**Comment by lostemples** [comment]
Hi, i got the same problem. How did you solve it ?
