### ISSUE TITLE
Could you share the training part for AM-softmax ? Thanks

### ISSUE THREAD

**Issue by YihangLou** [Joker316701882/Additive-Margin-Softmax#3]
Thanks for your sharing of Additive-Margin-Softmax, I hope to reproduce your impressing results. Could you share the code for training procedure?

**Comment by Joker316701882** [comment]
@YihangLou 
Will do soon!
Thank you : )

**Comment by Joker316701882** [comment]
@YihangLou 
Shared : ) open new issues if you meet questions!
