### ISSUE TITLE
Hi, another question

### ISSUE THREAD

**Issue by alexliyang** [Joker316701882/Additive-Margin-Softmax#4]
Hi, I use MS1M as train dataset , but I can only get acc = 0.73,  align is done on the dataset, imagesize = 224.

Is here any tricks?

**Comment by Joker316701882** [comment]
@alexliyang 
Not sure what happened there. Original image size is (112,96). It works fine with resface20, but with  224 input image size, receptive field may not be large enough to see the whole face. 
Two solutions:
1. Align your data with code provided in this repo, make sure size=(112,96).
2. Or try deeper network structure which may have enough receptive field size for large input image.
Hope it helps : )
