### ISSUE TITLE
ImportError: No module named models.resface

### ISSUE THREAD

**Issue by getengqing** [Joker316701882/Additive-Margin-Softmax#6]
Hello, I got the error when using the default 'train.py' file, but I saw the models file, I can see the resface.py, Why?

**Comment by GangqiangZhao** [comment]
Do not know why. But I solved it by including the resface.py path: 

 sys.path.append('*****/Additive-Margin-Softmax-master/models')

 network = importlib.import_module("resface")

**Comment by beautyni** [comment]
I got the same problem and I tried 
sys.path.append('*****/Additive-Margin-Softmax-master/models')

network = importlib.import_module("resface")
but it doesn't make sense. So how to deal with the problem?

**Comment by GangqiangZhao** [comment]
Have you append the correct path ( '*****/Additive-Margin-Softmax-master/models', replace ***** with your path )?

**Comment by Joker316701882** [comment]
@getengqing 
I add '__init__.py' in models file, seems problem has been solved.
